export const COMPONENTS = {
  MODAL_COMPONENT: 'MODAL_COMPONENT',
  H1_COMPONENT: 'H1_COMPONENT',
  H2_COMPONENT: 'H2_COMPONENT',
  PARAGRAPH_COMPONENT: 'PARAGRAPH_COMPONENT',
  LIST_COMPONENT: 'LIST_COMPONENT',
  BUTTON_COMPONENT: 'BUTTON_COMPONENT',
  LINK_COMPONENT: 'LINK_COMPONENT',
  BOX_COMPONENT: 'BOX_COMPONENT',
};